// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAshXPQO7RTn8BemHHF1A_nLOcW6dLkyw',
    appId: '1:348519163598:web:48853cb1382914217a929f',
    messagingSenderId: '348519163598',
    projectId: 'saranfarms-m',
    authDomain: 'saranfarms-m.firebaseapp.com',
    storageBucket: 'saranfarms-m.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ONmfXpnTdcqMiR6zfl6hZMlAgBQ8j6k',
    appId: '1:348519163598:android:879e550388de36877a929f',
    messagingSenderId: '348519163598',
    projectId: 'saranfarms-m',
    storageBucket: 'saranfarms-m.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9G44YNk4zwOn1O7rcpIAvwVwJzlvNqO8',
    appId: '1:348519163598:ios:abce55b8bde51f727a929f',
    messagingSenderId: '348519163598',
    projectId: 'saranfarms-m',
    storageBucket: 'saranfarms-m.appspot.com',
    iosClientId: '348519163598-7ecq1s794hvi03p5sikbiq9mt1i01v07.apps.googleusercontent.com',
    iosBundleId: 'com.example.saranfarms',
  );
}
